### ISSUE TITLE
Link to "Settings" is wrong

### ISSUE THREAD

**Issue by nico3333fr** [ProtonMail/proton-contacts#120]
![image](https://user-images.githubusercontent.com/2578321/63523494-8beddb00-c4fa-11e9-89c9-138384662d4c.png)

Should point to `/settings`

**Comment by econdepe** [comment]
Discussing with @nico3333fr and @mmso , it seems unclear where this link (we are talking about the `Settings` link in the top bar, between `Contacts` and `Support`) should point to. In the calendar app it's pointing currently to `calendar/settings`, so it would make sense that it's `contacts/settings` here too. Having a link to `/settings` in there would be counter-intuitive IMO.

**Comment by nico3333fr** [comment]
My mistake: I though it was a bug (the search bar disappeared, the nav also).

**Comment by mmso** [comment]
Closing this
