### ISSUE TITLE
Looks like a wrong function call is happening

### ISSUE THREAD

**Issue by vladimiry** [ProtonMail/proton-contacts#152]
This function:
https://github.com/ProtonMail/proton-contacts/blob/b2b2c887d3a6bb90b763739f66684ca4df48d65f/src/app/helpers/encrypt.js#L111
Is being called the following way (passing 3 args):
https://github.com/ProtonMail/proton-contacts/blob/b2b2c887d3a6bb90b763739f66684ca4df48d65f/src/app/components/merge/MergeModal.js#L131
https://github.com/ProtonMail/proton-contacts/blob/b2b2c887d3a6bb90b763739f66684ca4df48d65f/src/app/components/merge/MergeContactPreview.js#L39

**Comment by econdepe** [comment]
Yeah, the way to call that function has been changed. See #136.

**Comment by vladimiry** [comment]
By the way, using TypeScript or/and advanced code analyzing (like for example LGTM: [1](https://lgtm.com/projects/g/ProtonMail/proton-contacts/snapshot/c81d0bb9648606985776e659005805c808d03d0c/files/src/app/components/merge/MergeContactPreview.js?sort=name&dir=ASC&mode=heatmap#L39), [2](https://lgtm.com/projects/g/ProtonMail/proton-contacts/snapshot/c81d0bb9648606985776e659005805c808d03d0c/files/src/app/components/merge/MergeModal.js?sort=name&dir=ASC&mode=heatmap#L131)) could prevent similar issues to happen, without human effort involved.

**Comment by EpokK** [comment]
We plan to use `TypeScript` later.
