### ISSUE TITLE
Support text is not readable

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#159]
The `Support` button in the toolbar is not properly aligned and the text is not readable:

![Screenshot_5](https://user-images.githubusercontent.com/44697797/65881140-3fb47700-e393-11e9-8a07-7d933a3a79d5.png)

**Comment by matstaz** [comment]
@emnproton I will create a new ticket for this since there are other changes I need Edu to perform. I will obviously include this bug. Closing this issue for now
