### ISSUE TITLE
V4 polish - Update welcome message (free/paid)

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/proton-contacts#164]
Paid
- update design and iconography to follow: https://app.zeplin.io/project/5bb1deae290afc111d140a3f/screen/5d2446107231e02e02cedeea

Free
- leverage same content as Paid (except the last column)

Import contacts
Add contacts to your ProtonMail account by importing them from a CSV or vCard file.
[Import]

Export contacts
Create an backup of your ProtonMail contacts by exporting them to a vCard file.
[Export]

Unlock features
Upgrade to a paid plan to enable encrypted contact details and manage contact groups.
[Upgrade]

I will ask Milda to design something for this in line with eht paid design

Upgrade should bring user to settings > dashboard and fire off the upgrade modal

**Comment by econdepe** [comment]
I think the link for the paid user is not correct. Probably it's this other one: https://app.zeplin.io/project/5bb1deae290afc111d140a3f/screen/5d2448d7cdd9d2998cbbb3dd
