### ISSUE TITLE
V4 polish - delete contacts must be updated to be more of a warning

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/proton-contacts#169]
for delete contacts, I would like to change the modal to say the following:

Modal title: Delete contacts
Warning text: « This action will permanently delete selected contacts. Are you sure you want to delete contacts? »
Buttons: Cancel (secondary) / Delete (red)

In case of a doubt, check with Richard the styling of the warning text and the buttons. they should match what he has done for Mail delete that him and I discussed.

**Comment by econdepe** [comment]
Ok. Two questions:
1) For the text of the warning, do you want "... you want to delete contacts" or "... you want to delete these contacts". Also, for only one contact, what the text should be: "This action will permanently delete the selected contact. Are you sure you want to delete this contact?" ?
2) It seems the color has been chose for warning in the React repos and the design system is yellow, while red is reserved for error. Do you still want to go for red?

**Comment by matstaz** [comment]
1. yes. If you can differentiate 1 vs multiple then I would follow your approach.

2. the button I feel needs to be red. but you can use the orange for the text like here

![Capture d’écran 2019-10-08 à 15 38 03](https://user-images.githubusercontent.com/40168570/66400392-abc15b80-e9e1-11e9-8423-355472f3811e.png)

**Comment by matstaz** [comment]
Modal title: Delete contact
Warning text: « This action will permanently delete the selected contact. Are you sure you want to delete this contact? »
Buttons: Cancel (secondary) / Delete (red)

Modal title: Delete emails
Warning text: « This action will permanently delete the selected contacts. Are you sure you want to delete these contacts? »
Buttons: Cancel (secondary) / Delete (red)
