### ISSUE TITLE
V4 polish - update the create / edit modal with UX/UI improvements

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/proton-contacts#170]
On the modal, we need to make sure everything is properly vertically aligned.

<img width="708" alt="Capture d’écran 2019-10-04 à 13 59 00" src="https://user-images.githubusercontent.com/40168570/66206164-91207700-e6af-11e9-98ac-c9c8719ed937.png">

Also, we need to make sure that Phone numbers and addresses can be ordered since it impacts what is displayed in the summary. it is missing right now.

Finally, we need to make sure that addresses input fields follow the component (placeholder text inside the box not outside). also their might be a spacing issue between 1 address and the other.

<img width="575" alt="Capture d’écran 2019-10-04 à 14 03 03" src="https://user-images.githubusercontent.com/40168570/66206321-0db35580-e6b0-11e9-98fe-af4a48bb2247.png">

Finally, I would not automatically add text input except for email address.

For everything else, the user would have to click on "add" first. This is to align with free user experience

**Comment by EpokK** [comment]
@econdepe I did the change for `placeholder` in address fields and some alignment. I let you add the sort on `tel` and `adr`.

**Comment by econdepe** [comment]
Adding the `sort` is easy (I opened the PR #190), but the alignment is still tricky. A dirty solution I used in #187 was to introduce a width by hand.

**Comment by matstaz** [comment]
@econdepe please make sure at least this is not forgotten

> Also, we need to make sure that Phone numbers and addresses can be ordered since it impacts what is displayed in the summary. it is missing right now.

**Comment by econdepe** [comment]
Sure, the sorting feature is already in #190. Let me come back to that PR to complete it
