### ISSUE TITLE
Storage counter is not correct

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#174]
When I login to two different test accounts, I get the following storage info:

![Screenshot_6](https://user-images.githubusercontent.com/44697797/66213995-224c1980-e6c1-11e9-900c-b03fa59bc2a7.png)

![image (2)](https://user-images.githubusercontent.com/44697797/66213996-22e4b000-e6c1-11e9-8d37-894843d91348.png)

**Comment by econdepe** [comment]
Haha, this is not a bug in contacts, but just everywhere. It's simply because the corresponding react-component is rounding either to 0 or 1, instead of from 0 to 100. I will post a fix there.
