### ISSUE TITLE
V4 polish - Multi-selection imagery

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/proton-contacts#181]
We should leverage the way we display imagery when selecting group but when selecting multiple contacts instead of just a line of text. We can follow the same pattern as shown below.

![Site - Group - Filter Contacts - 1(1)](https://user-images.githubusercontent.com/40168570/66322936-3ee78c00-e923-11e9-83bf-956cc3b6033b.png)

Picture will be provided by Milda.

(No header)
You selected X contacts from your address book.
Picture
[Deselect all] [Export all]

**Comment by matstaz** [comment]
Here are the images to use (svg can be extracted)

single contact
- https://app.zeplin.io/project/5bb1deae290afc111d140a3f/screen/5d9f5550f76d0e2fa23fc70b
multiple contacts
- https://app.zeplin.io/project/5bb1deae290afc111d140a3f/screen/5d9f5550a4849708155bea3b

**Comment by econdepe** [comment]
Sounds good. I guess the fact that the image is the same as for the contact groups is a choice you have made on purpose

**Comment by matstaz** [comment]
yes the image is intentionally the same. The message and actions however are different
