### ISSUE TITLE
Ratio avatar is broken if the image w!=h

### ISSUE THREAD

**Issue by dhoko** [ProtonMail/proton-contacts#195]
A square, we have something nice:

![Screenshot from 2019-10-11 18-20-06](https://user-images.githubusercontent.com/713283/66667689-e7fbf280-ec53-11e9-8d95-bc6fa87ebdd2.png)

Not a square:

![Screenshot from 2019-10-11 18-18-18](https://user-images.githubusercontent.com/713283/66667687-e7fbf280-ec53-11e9-81bc-ae1a085b6be3.png)
![Screenshot from 2019-10-11 18-18-33](https://user-images.githubusercontent.com/713283/66667688-e7fbf280-ec53-11e9-8dd1-21dc118ac73f.png)

Btw, what's the limit when we upload an image ?

**Comment by nico3333fr** [comment]
This can be fixed using `ratio-container-square` wrapper and `inner-ratio-container h100 w100` on the image, but the button goes too low. Will see with @econdepe on Monday.
