### ISSUE TITLE
V4 responsive - settings content

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/proton-contacts#218]
Here is the concept we should try to reproduce as much as possible with as little amount of effort as possible (only second row is applicable to contact, first row is email. Also don't pay attention to the app footer extension for now since we only have 2 apps. check with @EpokK how he is implementing it in React)

-  [x] App logo sticky at the top of the side menu
-  [x] app bar sticky at the bottom of the side menu
-  [x] "settings" label in the top bar
-  [x] Contacts icons and account circle in the top bar
-  [x] email address and username in the account dropdown ONLY
-  [x] list of settings page in the left hand navigation menu

![Proton V4 - Responsive](https://user-images.githubusercontent.com/40168570/67014052-765cf200-f0f4-11e9-9b6f-3000e1e5cc84.png)

**Comment by EpokK** [comment]
@econdepe come to me when you start on that, I've already prepared a lot for us !
