### ISSUE TITLE
V4 polish - heigh of each row in the contact list must be reduced

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/proton-contacts#219]
Heigth is set to 76 pixels
It should be taken down to 71 pixels to match email list.

Priority set to high because there is a lot of white space. make sure content is properly aligned inside each row.

![Capture d’écran 2019-10-17 à 16 52 42](https://user-images.githubusercontent.com/40168570/67020560-ac9f6f00-f0fe-11e9-8a85-caea1f9970a3.png)

**Comment by nico3333fr** [comment]
Height is computed by `ReactVirtualized__Grid`, so it will be very difficult to update it without changing everything, cc @EpokK
