### ISSUE TITLE
PGP settings not available for free user

### ISSUE THREAD

**Issue by nikolanol** [ProtonMail/proton-contacts#221]
For free users, there is no option to edit Advanced PGP settings for a contact.

This setting should be available to all email addresses, regardless of whether the user is paid/free

![image](https://user-images.githubusercontent.com/49553343/67081857-4bc47500-f198-11e9-9298-1e0a253508fc.png)

**Comment by econdepe** [comment]
I saw this the other day, but I thought that was intended. But indeed in v3 it does not work like this. @EpokK will know for sure. I opened PR #223 for a fix
