### ISSUE TITLE
First date in list is shown with time

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#228]
**Summary:**

If you add a birthday/anniversary or other field which accepts date values, the first such date field that you enter is going to feature the selected date + time with seconds set to `00:00`.

**Expected behavior:**

Contacts with date fields shouldn't have a time set.

**Screenshot:**

![Screenshot_10](https://user-images.githubusercontent.com/44697797/67199075-a19b5600-f400-11e9-862f-c37b9e965c2a.png)

**Comment by econdepe** [comment]
Yeah, there's a bug in the code. But to fix this it's better to wait until https://github.com/ProtonMail/react-components/issues/116 is ready

**Comment by econdepe** [comment]
In the end I fixed the bug in the code. However, we have to come back to how dates are saved in the vcard when ProtonMail/react-components#116 is ready.
