### ISSUE TITLE
Tooltips missing in contact view

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#229]
**Summary:**

We're missing tooltips on mouse over on the three buttons in Contact Details View.

**Example:**

![Screenshot_11](https://user-images.githubusercontent.com/44697797/67204701-67d14c00-f40e-11e9-8646-40746462849f.png)

Notice how on mouse over there are no tootips for these buttons.

**Comment by matej-n** [comment]
Also, please add a tooltip on the contacts button as i think it will be hard for the users to find it.

![contacts-tooltip](https://user-images.githubusercontent.com/31239087/67205957-14acc880-f411-11e9-88bd-73cda2fd721d.jpg)

**Comment by emnproton** [comment]
@matej-n Opened a separate issue for that in the Angular project, as that's a separate app.

Link: https://github.com/ProtonMail/Angular/issues/9172

**Comment by matstaz** [comment]
@matej-n , @emnproton we discussed this with Richard and we tried the tooltips in both areas. I raised that comment. Unfortunately, the tooltips looked like shit so we decided to stick with the native browser functionality. cc @EpokK for info.

**Comment by matej-n** [comment]
To be honest even i did not know what they were for. I tried clicking on them to find out. IMHO the experience will be even worse for the users.

**Comment by emnproton** [comment]
@matstaz Sure thing, if you've guys already decided on this part the design, do close the issue (and the Angular one as well).

**Comment by matstaz** [comment]
We will have it done. Aurélien already coded this in Angular mail and I opened a ticket in react-component project
