### ISSUE TITLE
V4 extra polish - improve the UX for pictures

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/proton-contacts#231]
### Step 1: upon selecting "photo" from the dropdown
- [x] instead of showing this icon, can we have a "select photo" button
- [x] remove the dropdown with the edit button in there (only as long as file is not uploaded)

![Capture d’écran 2019-10-22 à 09 30 12](https://user-images.githubusercontent.com/40168570/67266391-72442200-f4b0-11e9-8568-65573ee14ddb.png)

![Capture d’écran 2019-10-22 à 09 30 04](https://user-images.githubusercontent.com/40168570/67266367-622c4280-f4b0-11e9-88b7-23ec0ecc0be3.png)

### Step 2: upon uploading the image
- [x] upon uploading the image, can we show the image right away rather than having the button? I just uploaded it so it would be ideal to see it. I understand that it is different if I access the read view and request to decrypt the picture
- [ ] the dropdown appears with the ability to "edit" but do we need the "clear" feature though. If I edirt

![Capture d’écran 2019-10-22 à 09 31 17](https://user-images.githubusercontent.com/40168570/67266496-af101900-f4b0-11e9-8630-ab9b5189805a.png)
![Capture d’écran 2019-10-22 à 09 31 25](https://user-images.githubusercontent.com/40168570/67266507-b20b0980-f4b0-11e9-8d01-e247e9820aa4.png)

### Step 3: upon saving the create/edit form
- [x] can we display the circle (like when there is no picture) and put the "load photo" button (primary blue text) inside the circle.
- [x] rename the `load image` to `load photo`
- [x] can we make sure the photo retains a perfect circle shape

![Capture d’écran 2019-10-22 à 09 31 39](https://user-images.githubusercontent.com/40168570/67266642-fd251c80-f4b0-11e9-84a2-a1d47325299f.png)
![Capture d’écran 2019-10-22 à 09 31 49](https://user-images.githubusercontent.com/40168570/67266648-00200d00-f4b1-11e9-974b-02980117e21b.png)

**Comment by econdepe** [comment]
All the fields in the vcard, including the image ones, are decrypted when clicking on the contact. So I'm not sure if it does make much sense to use display the `Load image` button here. I mean, it's a design decision, not so much a performance one

**Comment by econdepe** [comment]
In step 2:

> the dropdown appears with the ability to "edit" but do we need the "clear" feature though. If I edirt

Well, it's true that the user can open the "edit" modal and clear the image URL field. But it's not as intuitive and fast (the string in the image URL field is quite long and my PC e.g. lags a bit when selecting it) as having the "clear" button. A re-ordering of the actions may be nice though. Having "delete" as default is not great since it will directly erase my picture if I click it by mistake.
