### ISSUE TITLE
Multiple emails shown in contact group edit modal

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#253]
Summary:

When adding additional emails to a contact group, we show all the emails from a contact inside a single-line in the dropdown.

The `add to contact group` modal should show a single email per line.

**Example:**

![Screenshot_10](https://user-images.githubusercontent.com/44697797/67460121-861b8f80-f63a-11e9-8637-755f40f35e88.png)

**Note:**

I think this feature got broken while fixing https://github.com/ProtonMail/proton-contacts/issues/237

**Comment by EpokK** [comment]
This is correct, we display `${Email} ${Name}`, if the `Email` equals `Name` you are seeing 2 times the email value.

**Comment by emnproton** [comment]
Verified as fixed.
