### ISSUE TITLE
`No results page` isn't responsive on mobile devices

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#258]
**Summary:**

The `no results page` is not responsive on mobile devices.

**Example:**

![Screenshot_13](https://user-images.githubusercontent.com/44697797/67470927-dbfa3280-f64e-11e9-8fd8-8b6f769e4cde.png)

**Comment by matstaz** [comment]
@econdepe  I think the same applies to "no contact in address book"
