### ISSUE TITLE
No results found single column 

### ISSUE THREAD

**Issue by dhoko** [ProtonMail/proton-contacts#263]
1. Open contacts
2. Search a contact
3. Select the contact
4. Delete the contact
5. :tada: 

URL: https://beta.protonmail.com

![Screenshot from 2019-10-24 17-02-21](https://user-images.githubusercontent.com/713283/67498767-52635880-f680-11e9-9709-5c0671360d9d.png)

**Comment by econdepe** [comment]
This is already fixed in the master branch

**Comment by dhoko** [comment]
Fix available on v4
