### ISSUE TITLE
Autosave toggle status is updated only after page refresh

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#266]
**Summary:**

If you enable/disable the contact autosave toggle, the change will be shown only after a page refresh.

**Steps to reproduce:**

> Navigate to ProtonContacts > Contacts Settings > Toggle Automatically save contacts to ON or OFF > click on Contact Groups and then go back to General.
> 
> The toggle will not be changed and to see the change, you will have to go to your mailbox for the changes to be applied.

**Example:**

![mVbxShJUcn](https://user-images.githubusercontent.com/44697797/67554902-8d14d180-f710-11e9-91a3-0d400c900632.gif)

**Comment by nikolanol** [comment]
Verified as fixed
