### ISSUE TITLE
Contacts are removed from contact group after merge

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#270]
**Summary:**

CS Report: https://proton.atlassian.net/browse/CLIENT-1712

If you have two or more contacts in contact groups, merging them will result in the contacts being removed from their corresponding contact groups.

**Steps to reproduce the bug:**

1. Have two or more duplicate contacts
2. Add the contacts that you are going to merge to a contact group.
3. Merge the contacts
4. Notice the merged contacts are removed from their contact group after the merge

**Video:**
https://recordit.co/Fu7YIQFttM

**Comment by nikolanol** [comment]
Verified as fixed
