### ISSUE TITLE
`Other informations` doesn't display everything

### ISSUE THREAD

**Issue by dhoko** [ProtonMail/proton-contacts#272]
<img width="1120" alt="Screenshot 2019-10-26 at 14 26 38" src="https://user-images.githubusercontent.com/713283/67619643-4e5d4500-f7fe-11e9-94dc-47912822a018.png">
<img width="628" alt="Screenshot 2019-10-26 at 14 36 44" src="https://user-images.githubusercontent.com/713283/67619644-4e5d4500-f7fe-11e9-97ca-a2a26058c571.png">

cf ^ I added a logo but I can't see it. 

Env:
URL: beta/v4
Chrome Version 78.0.3904.70 (Official Build) (64-bit)
Mac OSX 10.14.5 (18F132)

**Comment by emnproton** [comment]
Verified as fixed.
