### ISSUE TITLE
Counter-intuitive clear search on responsive view

### ISSUE THREAD

**Issue by econdepe** [ProtonMail/proton-contacts#275]
On the responsive view (mobile), if I do a search and get a few hits, it's quite unclear how to clear it (I have to open the search again, which doesn't display anything, and enter the empty string).

View after searching 'ma', clicking on search again:
![image](https://user-images.githubusercontent.com/33841139/67669014-57225800-f971-11e9-8280-494e9242624b.png)

We should maybe improve the UX. At least show the previous search upon re-opening the search.

List of improvements by @matstaz 
- [ ] in desktop view, show the X on the far right of the search bar
- [ ] in desktop view, make sure that long search query do not overlap with the X button once it is added
- [ ] in responsive view, show the `Search` title when the search is active like we do in Mail
- [ ] in responsive view, add in the dropdown the `Clear` button next to the `Search` button

**Comment by econdepe** [comment]
I guess I did not do a good description before :sweat_smile:

If I'm on the mobile view and:
1) While on the contact list view, do a search using the magnifier in the toolbar.
2) I get a few hits.
3) If I want to clear this search, how to do it?? There's no "clear search" button anywhere, and If I open the searchtool again it's empty. I actually have to click again on search (with the empty string on it), but this is very counter-intuitive

**Comment by matstaz** [comment]
@econdepe this is a good point

First of all, we shall follow what Mail app does, i.e. display in the header the tilte "Search"

![IMG_A29C84E77C8E-1](https://user-images.githubusercontent.com/40168570/68302116-a9662600-00a1-11ea-9011-cd47cd70cf45.jpeg)

Second, I recommend that next to the header we display in parentheses the word "clear" and it should look like an actionable link. Alternatively we can display under the main CTA in the drop down a "Clear search" link. This link would only appear if a search has been performed.

Searching for nothing (blank) could also clear the search btw.

**Comment by matstaz** [comment]
Updated with actions to be taken right away
