### ISSUE TITLE
Deleting a contact from a contact group redirects you to the main contacts list

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#283]
**Summary:**

CS Issue: https://proton.atlassian.net/browse/CLIENT-1749

After permanently deleting a contact from a contact group, you are redirected to the main "Contacts" tab right after deleting selected contacts within a contact group.

**Expected behavior** 

Not to be redirected to the main contact list, to stay in the same contact group. 

**Example:**

![OXXDCTrmYp](https://user-images.githubusercontent.com/44697797/67682480-c0b15f00-f98f-11e9-82c4-0691d5b33146.gif)

**Comment by nikolanol** [comment]
Verified as fixed
