### ISSUE TITLE
Add search by email address

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#284]
**Summary:**

CS Report: https://proton.atlassian.net/browse/CLIENT-1756

Currently, we do not allow the search of contacts by their email address. This is a regression from v3 functionality.

**Example:**

![image](https://user-images.githubusercontent.com/44697797/67747908-12a6c300-fa2a-11e9-94b4-0843a87280b7.png)

**Comment by nikolanol** [comment]
Verified as fixed
