### ISSUE TITLE
More options in datepicker dropdown for 'Year'

### ISSUE THREAD

**Issue by nikolanol** [ProtonMail/proton-contacts#286]
_CS report: https://proton.atlassian.net/browse/CLIENT-1759_

Contact birthday/anniversary year can only be scrolled through by clicking. When selecting the year of a contact's birthday or anniversary, you are only shown the 10 years before or after the current year. To view the previous ones, you have to click on a year to select it and then bring up the menu again to select it again.

![image](https://user-images.githubusercontent.com/49553343/67760497-bc457e80-fa41-11e9-9455-e497fd80f01b.png)

**Comment by EpokK** [comment]
We plan to revamp this component with our own.
