### ISSUE TITLE
No Advanced settings when creating or adding addresses to a contact

### ISSUE THREAD

**Issue by nikolanol** [ProtonMail/proton-contacts#287]
_CS report: https://proton.atlassian.net/browse/CLIENT-1757_

There is no option to open the Advanced contact settings in the Add contact modal to add a PGP key to an address. Instead, this now requires additional steps to locate the saved contact and then add a public key.

V3:
![image](https://user-images.githubusercontent.com/49553343/67766086-f1f06480-fa4d-11e9-89ad-fbacb87fba74.png)

V4:

![image](https://user-images.githubusercontent.com/49553343/67766093-f87edc00-fa4d-11e9-8ff2-34cfd698cb9c.png)

**Comment by EpokK** [comment]
This is expected to avoid issues when the contact is not yet saved.

> now requires additional steps to locate the saved contact

@econdepe addded a fix recently to open the contact recently created.
