### ISSUE TITLE
Typo in clear search screen

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#302]
**Summary:**

In the clear search screen that appears when no contact results have been found,  there is a blank space between the last word in the sentence and the period.

**Screenshot:**

![image](https://user-images.githubusercontent.com/44697797/68120842-9cf99600-ff06-11e9-8a41-6546f5eaade7.png)

**Comment by nikolanol** [comment]
It needs a space after 'or'

![image](https://user-images.githubusercontent.com/49553343/68213318-9ee15900-ffdb-11e9-9323-11a10bd8a270.png)

For consistency, we can make it Bold, like in mail:

![image](https://user-images.githubusercontent.com/49553343/68213609-3050cb00-ffdc-11e9-9951-7bff941b26ae.png)
This also needs to be aligned.
