### ISSUE TITLE
App crash when too many fields are added

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#311]
If you keep adding fields in the `Other information` section, eventually the app crashes.

**Env:**

Windows 10 x64
Chrome 78
1920x1080 @ 125%

**Example:**

![3oxY23TLgE](https://user-images.githubusercontent.com/44697797/68305351-d1f11e80-00a7-11ea-88d5-8746c4503b54.gif)

**Comment by EpokK** [comment]
Are you sure the app is not crashing?

**Comment by emnproton** [comment]
@EpokK Yes, it's a crash, checked the logs, will edit desc.

**Comment by DaraQA** [comment]
it's not related with adding too many fields, only if you add `Birthday` or `Anniversary` the app crashes

**Comment by econdepe** [comment]
Yeah, this is happening because of the recent migration of the date libraries. This issue will be solved as https://github.com/ProtonMail/proton-contacts/issues/233 is closed
