### ISSUE TITLE
'Mobile' type numbers are shown as 'Cell'

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#321]
If you have a phone number as type `mobile`, the contact preview screen is going to show the same phone number as `cell`.

**Example:**

![qHtviEiuFI](https://user-images.githubusercontent.com/44697797/68567622-b85e2700-0459-11ea-9360-ff058c624397.gif)

**CS Report:** https://proton.atlassian.net/browse/CLIENT-1821

**Comment by DaraQA** [comment]
Not fixed 
![image](https://user-images.githubusercontent.com/50198984/68775178-64f10200-062e-11ea-9c77-004ced1ba81e.png)

**Comment by econdepe** [comment]
That seems strange. @DaraQA , could you share an account where this is happening?

**Comment by DaraQA** [comment]
Verified as fixed
