### ISSUE TITLE
Address info is considered case-sensitive during merge

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#323]
**Summary:**

If you are merging a contact with duplicate info, address info is going to be treated as case-sensitive.

That means that street names or other address info with different character case is going to be duplicated in the newly created contact.

**Example:**

![image](https://user-images.githubusercontent.com/44697797/68586905-0557f280-0486-11ea-9abd-57920693e2c4.png)

**Comment by matstaz** [comment]
Should we actually fix this?

**Comment by econdepe** [comment]
I think for the address field it makes sense to ignore capitalization

**Comment by jovanjovanovski** [comment]
Same happens with email addresses:

![Screen Shot 2019-11-21 at 16 38 36](https://user-images.githubusercontent.com/16116122/69352628-87fa6200-0c7d-11ea-9bc1-670b4404526d.png)

contact preview keeps both addresses even though the only difference is the first letter which is capitalized on one contact and not on the other:

![Screen Shot 2019-11-21 at 16 39 11](https://user-images.githubusercontent.com/16116122/69352678-a1031300-0c7d-11ea-9955-525ad37acfd1.png)

**Comment by econdepe** [comment]
Yeah @jovanjovanovski , we're aware of this and we plan to keep capitalization-sensitive email addresses. See the discussion in #285 ;)
