### ISSUE TITLE
V4 beta feedback - when searching in a contact group and no results is shown, wrong placeholder appears

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/proton-contacts#324]
The wrong image and placeholder text appears when you perform a search within a group.
<img width="1395" alt="Capture d’écran 2019-11-11 à 15 12 55" src="https://user-images.githubusercontent.com/40168570/68593621-24f71700-0496-11ea-8539-73935b9eccd7.png">

**Comment by econdepe** [comment]
Fixed via #320
