### ISSUE TITLE
V4 beta feedback - Select all / unselect all does not work in a group

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/proton-contacts#326]
When I have a group selected and select all contacts in the group, then the checkbox in the tool bar does not get automatically populated.

please verify:
- if not all the contacts are selected, the user can click on the checbox to select all contacts
- if all contacts are selected, the user can see the checkbox populated
- if the checkbox is populated (i.e. all contacts are selected), the user can click on the checkbox to deselect all contacts

<img width="716" alt="Capture d’écran 2019-11-11 à 15 14 07" src="https://user-images.githubusercontent.com/40168570/68594103-22e18800-0497-11ea-88aa-b334b54df04e.png">

**Comment by econdepe** [comment]
Fixed via #320
