### ISSUE TITLE
When contact is opened, the delete button is disabled

### ISSUE THREAD

**Issue by DeepSpaceHarbor** [ProtonMail/proton-contacts#345]
**CS Report**
https://proton.atlassian.net/browse/CLIENT-1887

**Steps to reproduce**
1. Go to /contacts
2. Open any contact
3. Click on the delete button

**Expected behavior**
The contact should be deleted.

**Current behavior**
Nothing happens, the button is disabled.

**Comment by econdepe** [comment]
Fixed by #340 (not deployed yet)
