### ISSUE TITLE
Unable to import a specific .csv file

### ISSUE THREAD

**Issue by DeepSpaceHarbor** [ProtonMail/proton-contacts#349]
**Summary**
During testing, I came across a .csv file that can't be uploaded. 
Due to the nature of the content inside the file, I can't share it publicly, but feel free to contact me in private if you are unable to reproduce the error.

**Steps to reproduce**
1. Clear all contacts
2. Upload the csv fule
3. 🍿

**Current behavior**
Uploading is stuck at 99%. 

**Screenshot**
![image](https://user-images.githubusercontent.com/11393457/69876661-738f1880-12c0-11ea-85bd-0262ebe857a9.png)

**Comment by econdepe** [comment]
The problem here happens to be the same as the one described in #350 :sweat_smile:
