### ISSUE TITLE
Copy contact group

### ISSUE THREAD

**Issue by EpokK** [ProtonMail/proton-contacts#356]
It would be nice if we can copy/duplicate a contact group. For example, I need to make contact groups for all the clients that I onboarded via phone and a separate one which will contain all the clients that got in touch with me.

Both of those groups contain the same addresses (or at least 99% of them), clients who received a call, had to get in touch with me via email first.

### Describe the solution you'd like
Simple Copy (duplicate) Address Group option

**Comment by mtjmohr25** [comment]
Just the same with me. I have a basis of say 50 contacts in one major group from which I need to create subgroups for various topic-related differentiations as I need to keep persons separate and do not want to fail in doing so.

Is there any solution in sight?
