### ISSUE TITLE
Review notification text when adding & removing contact group

### ISSUE THREAD

**Issue by DeepSpaceHarbor** [ProtonMail/proton-contacts#358]
**Summary**
When you add or remove a contact group you always see the same notification text.
![image](https://user-images.githubusercontent.com/11393457/70036304-c9abd680-15b4-11ea-944f-1a82eb2c1259.png)
`Contact group apply` , although it's clear, it's not the best user experience. I think we can do better.

**Comment by econdepe** [comment]
Yeah, I also thought these messages were not great. What's your opinion, @matstaz ?
