### ISSUE TITLE
Update logotype

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/proton-contacts#368]
Here is the compressed version:
[Logo.zip](https://github.com/ProtonMail/proton-contacts/files/3956773/Logo.zip)

**Comment by econdepe** [comment]
@matstaz , three questions/comments:
1) The new logo looks very similar to the one we currently have in https://beta.protonmail.com/contacts/ . My untrained eye probably can't tell the difference, but just asking to be sure.
2) We need the logo in size 148x36. The one provided is 134x14.
3) I don't see the app bar icon in the zip. I think we should just use the favicon from  #342, right?

**Comment by econdepe** [comment]
test server: https://v4.protonmail.blue

**Comment by econdepe** [comment]
Closed via https://github.com/ProtonMail/react-components/pull/496
