### ISSUE TITLE
List of issues found with dark mode

### ISSUE THREAD

**Issue by nico3333fr** [ProtonMail/proton-contacts#370]
Please centralize here issues found with Dark mode

**Comment by DeepSpaceHarbor** [comment]
- [ ] The colors have white outline

![image](https://user-images.githubusercontent.com/11393457/70892738-01ba0d00-1fea-11ea-98ee-ce5e954a2427.png)

**Comment by DeepSpaceHarbor** [comment]
- [ ] The hover style when selecting contact. 

![image](https://user-images.githubusercontent.com/11393457/70904920-de4f8c00-2002-11ea-9783-0a3fcb00cf5d.png)

**Comment by matej-n** [comment]
- [ ] The color of the text on a thread of new messages is white on white background:

![v4-dark-white](https://user-images.githubusercontent.com/31239087/71247743-a8b7e500-2319-11ea-97fe-a311b3508b22.jpg)

**Comment by econdepe** [comment]
The merge button only looks like a button when hovering over:
![image](https://user-images.githubusercontent.com/33841139/71477104-7e1dce80-27e8-11ea-83b9-359e3ffb011d.png)

![Screenshot 2019-12-26 14:06:58](https://user-images.githubusercontent.com/33841139/71477255-4e22fb00-27e9-11ea-91ce-3bf0dec9f913.png)

**Comment by nico3333fr** [comment]
All issues actually found have been fixed. Closing.
