### ISSUE TITLE
Sidebar  + Toolbar

### ISSUE THREAD

**Issue by EpokK** [ProtonMail/proton-contacts#40]
The sidebar and the toolbar are not display properly
<img width="1440" alt="Capture d’écran 2019-07-31 à 03 09 25" src="https://user-images.githubusercontent.com/1345786/62176344-5f063800-b341-11e9-92d8-a45a52ad6a1d.png">

**Comment by nico3333fr** [comment]
For the sidebar, it is fixed.

For the button, I ping-ed the design: you've used an `disabled` attribute on the button (which is semantically perfect, the accessibility-nazi that I am is happy 👍 ), but the design for disabled buttons is problematic.

![image](https://user-images.githubusercontent.com/2578321/62377794-bc69d700-b543-11e9-8214-4c1b63c15af0.png)
(the `disabled` one is more visible than active ones... 🤦‍♂  )

As far as I remember, I already pointed out this problem on Zeplin... anyway, I ping Mat to explain him the problem.

**Comment by nico3333fr** [comment]
We add the answer from design 
![image](https://user-images.githubusercontent.com/2578321/62383791-f097c480-b550-11e9-8b21-d644987a37f9.png)
Basically, an `opacity`. 

I fix it asap ^^ (just the time to look at what we did with @dhoko on Angular v4), if we can be consistent, it is better.
