### ISSUE TITLE
Cannot read property 'LabelIDs' of undefined error when opening a contact

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/proton-contacts#41]
**Summary**
When opening a contact, I got `Cannot read property 'LabelIDs' of undefined` error.

**Video**
https://recordit.co/6NWUtEHlXQ

**Screenshot**
![image](https://user-images.githubusercontent.com/11393457/62212112-6577cc80-b3a0-11e9-8885-e5af4fda39ff.png)

**Comment by EpokK** [comment]
API is [cleaning the email](https://www.w3schools.com/php/filter_sanitize_email.asp) value and remove `/`. I reported the issue to them. In the same time I applied a patch to avoid the issue on the UI.
