### ISSUE TITLE
Upload image button is missing

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#43]
Currently, it is not possible to upload an image to a contact.

**V4-dev:**

![Screenshot_3](https://user-images.githubusercontent.com/44697797/62213167-9d800f00-b3a2-11e9-9695-db18aa0129a3.png)

**Design-spec:**

![upload avatar](https://user-images.githubusercontent.com/44697797/62237976-53168680-b3d2-11e9-9c20-0ac7a632055e.jpg)

**Comment by EpokK** [comment]
We allow only the upload in the contact details modal, the design is not updated.
cf @matstaz
