### ISSUE TITLE
Cannot add a contact to a group

### ISSUE THREAD

**Issue by nikolanol** [ProtonMail/proton-contacts#44]
If you try to add a contact to a group a checkbox can't be checked. Also if Apply button is clicked there is a bad request.

http://g.recordit.co/2yDLU75P5J.gif

**Comment by emnproton** [comment]
Note: the same happens when using the top "add the group" button.

**Comment by EpokK** [comment]
Everything seems correct, I need to check deeper with @mmso ...

**Comment by mmso** [comment]
Fixed in https://github.com/ProtonMail/proton-contacts/commit/18357a20750061154afe1bba9637ea0a81470a9e

**Comment by emnproton** [comment]
Now we get `invalid input` notification when adding a contact to a contact group.

**Example:**

![Screenshot_4](https://user-images.githubusercontent.com/44697797/62681490-180be880-b9ba-11e9-92ab-f95f7a88bef7.png)
