### ISSUE TITLE
Composer doesn't handle clicks on mailto links

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#48]
If you click on a mailto link in the contacts view, instead of starting the composer, the system will try to start the default mail handling application.

**Steps to reproduce:**

1. Open a contact
2. Click on the email link in the contact view

**Screenshot:**

![Screenshot_5](https://user-images.githubusercontent.com/44697797/62218631-23a15300-b3ad-11e9-8e4c-79b6b551614d.png)

**Comment by EpokK** [comment]
Expected, we are not supported the composer in v4 since this part has not been moved in React yet.
