### ISSUE TITLE
Export button doesn't work

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#56]
On my main test account, clicking on the "Export" button in the sidebar leads to a blank grey page and a console error.

**Steps to reproduce:**

1. Go to contacts
2. Click on the export button in the sidebar
3. Notice the console error and failed event

Do contact me for test account info if not reproducible on your account.

**Example:**

![2019-07-31_21-36-45](https://user-images.githubusercontent.com/44697797/62242501-97f2eb00-b3db-11e9-921c-7454f60dd819.gif)

**Comment by EpokK** [comment]
Export button is not present in the sidebar.

**Comment by emnproton** [comment]
The export button in the right part of the screen also doesn't work and displays the same error.

**Example:**
![PAW6U7U7VE](https://user-images.githubusercontent.com/44697797/62680009-8484e880-b9b6-11e9-8c41-99149549c444.gif)
