### ISSUE TITLE
Contact group name is cut-off

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#57]
The bottom part of some characters in a contact group name is cut-off.

**Steps to reproduce:**

1. Click on a few contact groups from the sidebar
2. Notice that some contact groups will have the bottom part of their letters cut-off in the view of the right-part of the screen.

**Screenshot:**

![cutoff text](https://user-images.githubusercontent.com/44697797/62242575-be188b00-b3db-11e9-8b27-cca9925d63b0.jpg)

**Comment by nico3333fr** [comment]
Yes, this is caused by vertical rythm formulas... I send a fix asap ^^
