### ISSUE TITLE
Not possible to delete a single contact

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#58]
If you have a single contact in your contact list (with just a name and no other data), the delete button in the toolbar won't work.

Instead, a `path not found` error is displayed.

**Steps to reproduce:**

1. Empty your contact list (use v3 if v4 delete all option is still broken)
2. Add a new contact with just a name and no other info
3. Select the contact
4. Click the delete button in the toolbar
5. Notice the error

**Example:**

![delete contact](https://user-images.githubusercontent.com/44697797/62243216-1dc36600-b3dd-11e9-899b-dddc4995aaaa.jpg)

**Comment by EpokK** [comment]
Should be fixed.

**Comment by emnproton** [comment]
The original issue is fixed, but now when you have one contact and you delete it, the contact is still going to be displayed:

![2019-08-08_20-20-04](https://user-images.githubusercontent.com/44697797/62727615-21c53880-ba1a-11e9-99b8-d1b24bc6d64c.gif)

Only a full-page refresh would remove the contact from the contact list.
