### ISSUE TITLE
Missing tooltip info on encryption lock

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#62]
The encryption lock that appears after some data types (like `phone` or `other information`) is missing a tooltip on mouseover.

Without the tooltip, the lock can be confusing. I guess the black color is a placeholder until the final icon design is prepared.

**Steps to reproduce:**

1. Create a contact and add a note to it
2. Place the mouse over the black lock after the `Other information` label
3. Notice no tooltip appears
4. The same does not occur on v3

**V4-dev:**

![2019-07-31_222145](https://user-images.githubusercontent.com/44697797/62245480-0470e880-b3e2-11e9-8aed-8ff23779bc56.jpg)

**V3:**

![2019-07-31_222305](https://user-images.githubusercontent.com/44697797/62245484-05a21580-b3e2-11e9-852f-0d06716af8b1.jpg)

**Comment by EpokK** [comment]
@matstaz do you have the text for it please?
