### ISSUE TITLE
Delete button in toolbar doesn't work when contact is highlighted

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#67]
If you select a contact by clicking on it in the contact list, clicking on the delete button won't work. This may be counterintuitive from a UX perspective, as a user would expect that a  highlighted contact is regarded as being selected.

Currently, contacts can only be deleted if they are marked with the checkmark by clicking on their avatar image. Checkmarks are usually used for multi-selection, so it makes sense to make the delete button work when a single contact is highlighted.

**Steps to reproduce:**

1. Go to contacts
2. Open a contact by clicking on it in the contact list
3. Click the delete button in the toolbar
4. Nothing happens

**Example:**

![2019-08-02_16-15-49](https://user-images.githubusercontent.com/44697797/62376840-df938700-b541-11e9-9055-c57f556c7f46.gif)

**Comment by emnproton** [comment]
The delete button still doesn't work on opened contacts - only contacts that are selected with the checkbox can be deleted at the moment.

**Comment by EpokK** [comment]
Done.

**Comment by DaraQA** [comment]
The delete button does not work when the contact is highlighted and when the contact is marked.

https://recordit.co/BOV9TlCTkC
