### ISSUE TITLE
Contact list is not sorted after adding a new contact

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#68]
Adding a new contact doesn't refresh the contact list.

After adding a contact, you have to refresh the page in order to see the newly added contact.

Interestingly, this only happens with existing accounts that already have some contacts in the list. New accounts without 0 contacts do not have this problem. You can test this on the `qatester2` account.

I waited for a few minutes after adding a contact in case the list refreshes, but nothing happened after a few minutes.

**Steps to reproduce:**

1. Login to an account that already has some 30-50 emails in the contact list. Use `qatester2` if needed.
2. Go to contacts
3. Add a contact.
4. Notice the contact doesn't appear in the contact list

**Example:**

![2019-08-02_16-31-17](https://user-images.githubusercontent.com/44697797/62377847-dc999600-b543-11e9-9eeb-238fbea8e832.gif)

**Comment by mmso** [comment]
Does it appear at the end of the list probably?

**Comment by emnproton** [comment]
@mmso you're right - the list does get populated, but sorting happens after refresh.

Guess that behavior confused me, as on v4 sorting happens automatically after adding. Do close this ticket if sorting behavior doesn't need adjustment.

**v3:**

![2019-08-02_21-55-22](https://user-images.githubusercontent.com/44697797/62395368-4def3e00-b570-11e9-9435-2dcb96cefe7a.gif)

**Comment by mmso** [comment]
No we should sort it so good catch
