### ISSUE TITLE
Contacts can't be opened after removing a contact

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#70]
If you delete a contact, opening other contacts will not be possible.

Clicking on any contact will result in the default intro `You have X contacts in your address book` to stay on the right side of the view.

**Steps to reproduce:**

1. Select a contact with the checkmark
2. Delete the selected contact
3. Click on a different contact
4. Notice the right side of the screen doesn't show the contact info. The default contact intro view stays in the right part of the screen.

**Example:**

![2019-08-02_16-19-03](https://user-images.githubusercontent.com/44697797/62377950-094dad80-b544-11e9-9ada-126e1faf26da.gif)

**Screenshot:**

![s1](https://user-images.githubusercontent.com/44697797/62378365-f7203f00-b544-11e9-8175-2d24ccf0717d.jpg)

Notice in the screenshot, contact named `A5` is clicked, but not opened.

**Comment by EpokK** [comment]
Seems to be fixed now.
