### ISSUE TITLE
Possibly mistyped regular expressions

### ISSUE THREAD

**Issue by vladimiry** [ProtonMail/proton-contacts#82]
https://github.com/ProtonMail/proton-contacts/blob/f9c9f6125bb98eb01bc8be78fbe716d878865600/src/app/helpers/csvFormat.js#L60-L61

**Comment by econdepe** [comment]
Yeah, you're right. Thanks for pointing it out!

**Comment by vladimiry** [comment]
The potential issue is still there. Should not `[callback,telex]` be replace with `(callback|telex)`?

**Comment by econdepe** [comment]
yep! :sweat_smile:
