### ISSUE TITLE
Add to group long name display

### ISSUE THREAD

**Issue by nico3333fr** [ProtonMail/proton-contacts#87]
Seen in a snapshot in another issue from @emnproton :

![image](https://user-images.githubusercontent.com/2578321/62686935-04ff1580-b9c6-11e9-985f-d320342e7dfc.png)

The items in "Add to group" with long names are badly displayed (some `flex-no-shrink` class to add). Will fix it asap, this is easy.

**Comment by emnproton** [comment]
@nico3333fr Well spotted - didn't post it because I'm trying not to report too many design issues 😄

**Comment by nico3333fr** [comment]
I've seen it on Slack in the snapshot in the comment, so it would be too bad not to fix it :)

Yes, as a lot of things are not yet stabilized and we are very busy, design issues have less priority. But if we can spot and kill some, I like to do so :) 

(and it also makes me feel super smart while editing some react files - Dunning-Krueger effect https://en.wikipedia.org/wiki/Dunning%E2%80%93Kruger_effect :D )
