### ISSUE TITLE
Free users can access paid account feature (additional contact details)

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#94]
If you keep closing and entering phone number digits in the phone field as a free user, you'll be able to successfully create contacts with phone numbers, despite this feature not being offered to free users.

**Steps to reproduce:**

1. Log in as a free user
2. Go to contacts
3. Create a new account
4. Enter a phone number digit
5. Close the `Upgrade required` modal
6. Enter a new digit
7. Steps 4 to 6 can be repeated indefinitely

**Edit**: Just noticed that the same happens with the fields from the `Other Information` and `Address` section.

**Example:**

![2019-08-08_20-25-45](https://user-images.githubusercontent.com/44697797/62727943-de1efe80-ba1a-11e9-9580-c7ffdd18c3a4.gif)

**Comment by EpokK** [comment]
@mmso I'm having an issue with our modal: when I open `ConfirmModal` I'm seeing the input change, if I return just `false`, it works, it stop the update.

```jsx
const hasRequirement = (field) => {
        if (['fn', 'email'].includes(field) || user.hasPaidMail) {
            return true;
        }

        if (!upgradeModalRef.current) {
            upgradeModalRef.current = true;
            createModal(
                <ConfirmModal
                    title={c('Title').t`Upgrade required`}
                    onConfirm={() => {
                        redirectTo('/settings/subscription');
                        upgradeModalRef.current = false;
                    }}
                    onClose={() => {
                        upgradeModalRef.current = false;
                    }}
                    confirm={c('Action').t`Upgrade`}
                >
                    <Alert type="warning">{c('Warning').t`This feature requires a paid Proton account`}</Alert>
                </ConfirmModal>
            );
        }

        return false;
    };

const handleChange = ({ uid: propertyUID, value, key = 'value' }) => {
        const { field } = properties.find(({ uid }) => uid === propertyUID) || {};
        const newProperties = properties.map((property) => {
            if (property.uid === propertyUID) {
                property[key] = value;
            }
            return property;
        });

        if (hasRequirement(field)) {
            setProperties(newProperties);
        }
    };
```

**Comment by mmso** [comment]
@EpokK it's because the old object displayed in the input gets mutated at `property[key] = value;`, even if the state is not set after. And it gets re-rendered with the mutated value when the modal is rendered.

Suggestion:
```js
        const newProperties = properties.map((property) => {
            if (property.uid === propertyUID) {
                return {
                    ...property,
                    [key]: value
                };
            }
            return property;
        });
```
