### ISSUE TITLE
Contacts with address info cannot be saved

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#98]
If you add an address (street, city, etc.) info to a contact, the changes will not be possible to be saved.

**Steps to reproduce:**

1. Edit an existing contact
2. Click the add button to add a new address
3. Fill in all the required addresses fields
4. Click save
5. Notice nothing happens

* The same behavior occurs when creating a new contact

**Example:**

![dRRpPrniAx](https://user-images.githubusercontent.com/44697797/62782853-6359f000-babb-11e9-9e95-4c91f5b43d21.gif)

**Comment by econdepe** [comment]
This has been fixed in #38 . See the changes to `src/app/components/ContactAdrField.js` there
